### ISSUE TITLE
Data availability for a tutorial class ?

### ISSUE THREAD

**Issue by loiseaujc** [mendezVKI/Lecture_10_VKI_PIV_PTV_LS#1]
Hi Miguel,

I am supposed to give a tutorial class this Friday (Jan. 14th) at Sorbonne Université about system identification and dimensionality reduction (essentially POD/DMD). As far as I understood, the class is intended for students from Ecole Navale. I have a dataset for the cylinder wake to illustrate the method but it has been obtained from a direct numerical simulation at low Reynolds numbers. I was wondering if you'd be ok if I use your PIV dataset? I think it would make much more sense for these particular students.

Thx a lot.

**Comment by mendezVKI** [comment]
Hello Jean-Christophe,

Sure no problem. I would be happy if you cite the source:

https://iopscience.iop.org/article/10.1088/1361-6501/ab82be

All the best!

Miguel

**Comment by loiseaujc** [comment]
Awesome ! I'll do cite this reference as well as your lecture notes.
I'm wrapping up the notebooks as we speak. Gotta finish them for tomorrow.

Thx a lot.
